version: '3.4'

services:
  tariffcomparison.server:
    image: ${DOCKER_REGISTRY-}tariffcomparisonserver
    build:
      context: .
      dockerfile: TariffComparison.Server/Dockerfile
    ports:
      - "8080:80"
